package is.project3.models;

/**
 * Represents a sales event in the system.
 *
 * <p>Philosophy:
 * This class models a real-world business event generated by customers.
 * Each instance represents a single sale action that occurred in the system.</p>
 *
 * <p>It is used as an INPUT model in the Kafka pipeline, meaning it is produced
 * by the SalesProducer and consumed by Kafka Streams for processing.</p>
 *
 * <p>This class is part of the "raw data layer" of the system, before any
 * aggregation or transformation is applied.</p>
 */

public class Sale {

    private String item;
    private double price;
    private int units;
    private String country;
    private long timestamp;

    public Sale() {
        // needed for JSON deserialization
    }

    public Sale(String item, double price, int units, String country, long timestamp) {
        this.item = item;
        this.price = price;
        this.units = units;
        this.country = country;
        this.timestamp = timestamp;
    }

    public String getItem() { return item; }
    public void setItem(String item) { this.item = item; }

    public double getPrice() { return price; }
    public void setPrice(double price) { this.price = price; }

    public int getUnits() { return units; }
    public void setUnits(int units) { this.units = units; }

    public String getCountry() { return country; }
    public void setCountry(String country) { this.country = country; }

    public long getTimestamp() { return timestamp; }
    public void setTimestamp(long timestamp) { this.timestamp = timestamp; }
}